version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - revive
    - gocyclo
    - cyclop
  disable:
    - staticcheck  # Disabled: QF1008 warnings are low-priority style suggestions

linters-settings:
  gofumpt:
    lang-version: "1.21"
    extra-rules: true
  revive:
    enable-all-rules: false
    rules:
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: true
  gocyclo:
    min-complexity: 15
  cyclop:
    max-complexity: 15
    skip-tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude all linter errors from test files
    - path: _test\.go$
      linters:
        - errcheck
        - revive
        - staticcheck

    # Exclude all linter errors from examples (except cyclomatic complexity)
    - path: examples/
      linters:
        - errcheck
        - revive
        - staticcheck
        - govet

    # Exclude all linter errors from internal test utilities
    - path: internal/testutil/
      linters:
        - errcheck
        - revive
        - staticcheck

    # Allow printf format directives in example code (examples demonstrate Printf usage)
    - text: "fmt.Print call has possible Printf formatting directive"
      linters:
        - govet

    # Allow SSEHandler name (stuttering is intentional for clarity)
    - text: "type name will be used as sse.SSEHandler"
      linters:
        - revive

    # Allow explicit embedded field access (clearer than implicit)
    - text: "QF1008"
      linters:
        - staticcheck

    # Allow SSE stuttering name export
    - text: "exported.*stutters"
      linters:
        - revive

run:
  timeout: 5m
  tests: false  # Don't run linters on test files
  skip-dirs:
    - vendor
    - examples

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

severity:
  default-severity: error
