name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Create Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Run tests
        run: go test -v ./...

      - name: Determine version bump
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)|breaking change|breaking:"
          minor_pattern: "(MINOR)|feat:"
          version_format: "${major}.${minor}.${patch}"
          change_path: "."
          namespace: ""
          bump_each_commit: false
          search_commit_body: true
          user_format_type: "csv"

      - name: Create Git Tag
        if: steps.semver.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a v${{ steps.semver.outputs.version }} -m "Release v${{ steps.semver.outputs.version }}"
          git push origin v${{ steps.semver.outputs.version }}

      - name: Generate Changelog
        if: steps.semver.outputs.changed == 'true'
        id: changelog
        run: |
          echo "## Changes in v${{ steps.semver.outputs.version }}" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          if [ -n "${{ steps.semver.outputs.previous_version }}" ]; then
            echo "### Commits since v${{ steps.semver.outputs.previous_version }}" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
            git log v${{ steps.semver.outputs.previous_version }}..HEAD --pretty=format:"- %s (%h)" --no-merges >> CHANGELOG.md || \
            git log --pretty=format:"- %s (%h)" --no-merges -n 20 >> CHANGELOG.md
          else
            echo "### Initial Release" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
            git log --pretty=format:"- %s (%h)" --no-merges -n 20 >> CHANGELOG.md
          fi
          echo "" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.semver.outputs.previous_version }}...v${{ steps.semver.outputs.version }}" >> CHANGELOG.md

      - name: Create GitHub Release
        if: steps.semver.outputs.changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.semver.outputs.version }}
          name: Release v${{ steps.semver.outputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          generate_release_notes: true
